const $=id=>document.getElementById(id);let config={},history=[],anatomy=null;
async function api(path,data){const r=await fetch(path,data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{});const result=await r.json();if(!r.ok)throw Error(result.error);return result;}
async function command(action,extra={}){try{await api('/command',{action,...extra});$('message').textContent='Command queued for a safe boundary.';}catch(e){$('message').textContent=e.message;}}
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>command(b.dataset.action));
$('start').onclick=async()=>{try{await api('/start',{});$('message').textContent='Worker starting. Closing this browser will not stop it.';}catch(e){$('message').textContent=e.message;}};
$('restart').onclick=()=>{if(confirm('Discard learned state and restart from anatomical initial weights?'))command('restart',{confirmed:true});};
$('control').onchange=()=>command('control',{value:$('control').value});$('speed').onchange=()=>command('speed',{value:+$('speed').value});
window.onkeydown=e=>{if(config.evaluation&&$('control').value==='human'&&['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();command('human',{value:e.key==='ArrowUp'?1:-1});}};
window.onkeyup=e=>{if(config.evaluation&&$('control').value==='human'&&['ArrowUp','ArrowDown'].includes(e.key))command('human',{value:0});};
function pong(s){const c=$('pong'),g=c.getContext('2d'),w=c.width,h=c.height,p=s.physics;g.clearRect(0,0,w,h);g.strokeStyle='#233342';g.setLineDash([4,8]);g.beginPath();g.moveTo(w/2,0);g.lineTo(w/2,h);g.stroke();g.setLineDash([]);g.fillStyle='#86d8bf';g.fillRect((p.paddle_x-.008)*w,(s.player_y-p.paddle_half)*h,.016*w,2*p.paddle_half*h);g.fillStyle='#94a9ba';g.fillRect((1-p.paddle_x-.008)*w,(s.opponent_y-p.paddle_half)*h,.016*w,2*p.paddle_half*h);g.fillStyle='#eef4f7';g.fillRect((s.ball[0]-p.ball_radius)*w,(s.ball[1]-p.ball_radius)*h,2*p.ball_radius*w,2*p.ball_radius*h);}
function metrics(s){const items=[['Step',s.step],['Phase',s.phase],['Hit shaping',s.alpha],['Points / misses',`${s.metrics.points} / ${s.metrics.misses}`],['Paddle hits',s.metrics.hits],['Reward',s.metrics.reward.toFixed(2)],['Throughput',`${(s.steps_per_second||0).toFixed(1)} steps/s`],['Device / environments',`${s.device} / ${s.environments}`],['Measured roster',`${s.neurons} neurons · ${s.edges} edges`],['Threshold',s.graph_threshold??'Fixture / unspecified'],['Actuator',s.activation.toFixed(3)],['Velocity',s.velocity.toFixed(3)]];$('metrics').replaceChildren(...items.flatMap(([k,v])=>{const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=v;return[dt,dd];}));history.push(s.steps_per_second||0);history=history.slice(-100);const c=$('chart'),g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);g.strokeStyle='#7bcbb3';g.beginPath();const max=Math.max(1,...history);history.forEach((v,i)=>{const x=i*c.width/99,y=c.height-8-v/max*(c.height-16);i?g.lineTo(x,y):g.moveTo(x,y);});g.stroke();}
function drawAnatomy(){if(!anatomy)return;const c=$('anatomy'),gl=c.getContext('webgl');if(!gl){$('anatomy-note').textContent='WebGL unavailable.';return;}const pts=anatomy.positions.map((p,i)=>({p,i})).filter(({p,i})=>Array.isArray(p)&&p.length===3&&p.every(Number.isFinite)&&(!$('population').value||anatomy.cell_types[i]===$('population').value));if(!pts.length){$('anatomy-note').textContent='No recorded positions for this selection.';gl.clear(gl.COLOR_BUFFER_BIT);return;}const xs=pts.map(x=>x.p[0]),ys=pts.map(x=>x.p[1]),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys);const coords=pts.flatMap(({p})=>[2*(p[0]-xmin)/Math.max(1,xmax-xmin)-1,1-2*(p[1]-ymin)/Math.max(1,ymax-ymin)]);const shader=(type,src)=>{const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);return s;};const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,'attribute vec2 p;void main(){gl_Position=vec4(p*.94,0.,1.);gl_PointSize=3.;}'));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,'precision mediump float;void main(){gl_FragColor=vec4(.48,.82,.71,1.);}'));gl.linkProgram(program);gl.useProgram(program);const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(coords),gl.STATIC_DRAW);const loc=gl.getAttribLocation(program,'p');gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,2,gl.FLOAT,false,0,0);gl.viewport(0,0,c.width,c.height);gl.clear(gl.COLOR_BUFFER_BIT);gl.drawArrays(gl.POINTS,0,pts.length);$('anatomy-note').textContent=`${pts.length} recorded positions · XY projection of selected subnetwork`;$('anatomy').onclick=e=>{const r=c.getBoundingClientRect(),x=2*(e.clientX-r.left)/r.width-1,y=1-2*(e.clientY-r.top)/r.height;let best=0,d=Infinity;pts.forEach((v,i)=>{const dist=(coords[2*i]*.94-x)**2+(coords[2*i+1]*.94-y)**2;if(dist<d){d=dist;best=i;}});$('body').value=anatomy.body_ids[pts[best].i];};}
$('population').onchange=drawAnatomy;$('inspect').onclick=async()=>{try{$('connections').textContent=JSON.stringify(await api('/connection?body='+encodeURIComponent($('body').value)),null,2);}catch(e){$('connections').textContent=e.message;}};
$('run-probe').onclick=()=>command('probe',{probe:{kind:$('probe').value,polarity:$('polarity').value,direction:+$('direction').value,speed:+$('probe-speed').value},silenced_types:$('silence').value.split(',').map(s=>s.trim()).filter(Boolean)});
async function poll(){try{const s=await api('/status');if(!s.waiting){$('status').textContent=s.stopped?'Stopped':s.paused?'Paused':'Running';pong(s);metrics(s);$('log').textContent=(s.logs||[]).join('\n')||'Worker active.';}else{$('status').textContent='Awaiting worker';}if(config.evaluation){const d=await api('/diagnostic');if(Object.keys(d).length)$('diagnostic').textContent=JSON.stringify(d,null,2);}}catch(e){$('status').textContent='UI disconnected';$('message').textContent=e.message;}setTimeout(poll,500);}
api('/config').then(async c=>{config=c;$('mode').textContent=`${c.evaluation?'Frozen evaluation':'Training'} · ${c.checkpoint}`;document.querySelectorAll('.evaluation').forEach(e=>e.hidden=!c.evaluation);document.querySelectorAll('.training').forEach(e=>e.hidden=c.evaluation);if(c.evaluation){anatomy=await api('/anatomy');[...new Set(anatomy.cell_types)].sort().forEach(t=>{const o=document.createElement('option');o.value=o.textContent=t;$('population').append(o);});drawAnatomy();}poll();}).catch(e=>$('message').textContent=e.message);
