const $=id=>document.getElementById(id);let config={},history=[],anatomy=null;
async function api(path,data){const r=await fetch(path,data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{});const result=await r.json();if(!r.ok)throw Error(result.error);return result;}
async function command(action,extra={}){try{await api('/command',{action,...extra});$('message').textContent='Command queued for a safe boundary.';}catch(e){$('message').textContent=e.message;}}
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>command(b.dataset.action));
$('start').onclick=async()=>{try{await api('/start',{});$('message').textContent='Worker starting. Closing this browser will not stop it.';}catch(e){$('message').textContent=e.message;}};
$('restart').onclick=()=>{if(confirm('Discard learned state and restart from anatomical initial weights?'))command('restart',{confirmed:true});};
$('control').onchange=()=>command('control',{value:$('control').value});$('speed').onchange=()=>command('speed',{value:+$('speed').value});
window.onkeydown=e=>{if(config.evaluation&&$('control').value==='human'&&['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();command('human',{value:e.key==='ArrowUp'?1:-1});}};
window.onkeyup=e=>{if(config.evaluation&&$('control').value==='human'&&['ArrowUp','ArrowDown'].includes(e.key))command('human',{value:0});};
function pong(s){const c=$('pong'),g=c.getContext('2d'),w=c.width,h=c.height,p=s.physics;g.clearRect(0,0,w,h);g.strokeStyle='#233342';g.setLineDash([4,8]);g.beginPath();g.moveTo(w/2,0);g.lineTo(w/2,h);g.stroke();g.setLineDash([]);g.fillStyle='#86d8bf';g.fillRect((p.paddle_x-.008)*w,(s.player_y-p.paddle_half)*h,.016*w,2*p.paddle_half*h);g.fillStyle='#94a9ba';g.fillRect((1-p.paddle_x-.008)*w,(s.opponent_y-p.paddle_half)*h,.016*w,2*p.paddle_half*h);g.fillStyle='#eef4f7';g.fillRect((s.ball[0]-p.ball_radius)*w,(s.ball[1]-p.ball_radius)*h,2*p.ball_radius*w,2*p.ball_radius*h);}
function metrics(s){const items=[['Step',s.step],['Phase',s.phase],['Hit shaping',s.alpha],['Points / misses',`${s.metrics.points} / ${s.metrics.misses}`],['Paddle hits',s.metrics.hits],['Reward',s.metrics.reward.toFixed(2)],['Rally',`${s.rally_seconds.toFixed(2)} s`],['Tensor memory',`${(s.tensor_memory_bytes/1048576).toFixed(1)} MiB`],['Recorded spikes',s.metrics.spikes],['Local prediction MSE',(s.metrics.prediction_squared_error/Math.max(1,s.metrics.prediction_samples)).toExponential(3)],['Throughput',`${(s.steps_per_second||0).toFixed(1)} steps/s`],['Device / environments',`${s.device} / ${s.environments}`],['Measured roster',`${s.neurons} neurons · ${s.edges} edges`],['Threshold',s.graph_threshold??'Fixture / unspecified'],['Actuator',s.activation.toFixed(3)],['Velocity',s.velocity.toFixed(3)]];$('metrics').replaceChildren(...items.flatMap(([k,v])=>{const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=v;return[dt,dd];}));history.push(s.steps_per_second||0);history=history.slice(-100);const c=$('chart'),g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);g.strokeStyle='#7bcbb3';g.beginPath();const max=Math.max(1,...history);history.forEach((v,i)=>{const x=i*c.width/99,y=c.height-8-v/max*(c.height-16);i?g.lineTo(x,y):g.moveTo(x,y);});g.stroke();}
function evaluationViews(s){if(!s.events)return;const e=s.events,c=$('events'),g=c.getContext('2d');g.fillStyle=$('event-mode').value==='raw'?'#0b1118':'rgba(11,17,24,.25)';g.fillRect(0,0,c.width,c.height);e.pixels.forEach((p,i)=>{g.fillStyle=e.on[i]?'#86d8bf':'#efa376';g.fillRect((p%e.width)*c.width/e.width,Math.floor(p/e.width)*c.height/e.height,c.width/e.width,c.height/e.height);});const r=$('raster'),rg=r.getContext('2d'),prior=rg.getImageData(4,0,r.width-4,r.height);rg.clearRect(0,0,r.width,r.height);rg.putImageData(prior,0,0);rg.fillStyle='#86d8bf';(s.spiking_neurons||[]).forEach(i=>rg.fillRect(r.width-4,i/Math.max(1,s.neurons)*r.height,3,2));$('rates').replaceChildren(...Object.entries(s.population_rates_hz||{}).flatMap(([k,v])=>{const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=v.toFixed(2)+' Hz';return[dt,dd];}));}
let anatomyRenderer=null,recentSpikes=[];
function drawAnatomy(){
 if(!anatomy)return;
 const c=$('anatomy'),gl=c.getContext('webgl');
 if(!gl){$('anatomy-note').textContent='WebGL unavailable.';return;}
 if(!anatomyRenderer){
  const shader=(type,source)=>{const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);return s;};
  const program=gl.createProgram();
  gl.attachShader(program,shader(gl.VERTEX_SHADER,'attribute vec2 p;uniform float size;void main(){gl_Position=vec4(p*.94,0.,1.);gl_PointSize=size;}'));
  gl.attachShader(program,shader(gl.FRAGMENT_SHADER,'precision mediump float;uniform vec4 color;void main(){gl_FragColor=color;}'));
  gl.linkProgram(program);gl.useProgram(program);
  anatomyRenderer={program,buffer:gl.createBuffer(),point:gl.getAttribLocation(program,'p'),color:gl.getUniformLocation(program,'color'),size:gl.getUniformLocation(program,'size')};
 }
 const renderer=anatomyRenderer;
 const pts=anatomy.positions.map((p,i)=>({p,i})).filter(({p,i})=>Array.isArray(p)&&p.length===3&&p.every(Number.isFinite)&&(!$('population').value||anatomy.cell_types[i]===$('population').value));
 gl.viewport(0,0,c.width,c.height);gl.clear(gl.COLOR_BUFFER_BIT);
 if(!pts.length){$('anatomy-note').textContent='No recorded positions for this selection.';return;}
 const xs=pts.map(x=>x.p[0]),ys=pts.map(x=>x.p[1]),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys);
 const positions=new Map(pts.map(({p,i})=>[i,[2*(p[0]-xmin)/Math.max(1,xmax-xmin)-1,1-2*(p[1]-ymin)/Math.max(1,ymax-ymin)]]));
 function draw(vertices,mode,color,size){gl.useProgram(renderer.program);gl.bindBuffer(gl.ARRAY_BUFFER,renderer.buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(vertices),gl.DYNAMIC_DRAW);gl.enableVertexAttribArray(renderer.point);gl.vertexAttribPointer(renderer.point,2,gl.FLOAT,false,0,0);gl.uniform4fv(renderer.color,color);gl.uniform1f(renderer.size,size);gl.drawArrays(mode,0,vertices.length/2);}
 const edgeVertices=[],limit=+$('edge-limit').value;
 for(let e=0;e<Math.min(limit,anatomy.pre.length);e++){const a=positions.get(anatomy.pre[e]),b=positions.get(anatomy.post[e]);if(a&&b)edgeVertices.push(...a,...b);}
 draw(edgeVertices,gl.LINES,[.16,.24,.29,1],1);
 const coords=pts.flatMap(({i})=>positions.get(i));
 draw(coords,gl.POINTS,[.48,.82,.71,1],3);
 draw(recentSpikes.filter(i=>positions.has(i)).flatMap(i=>positions.get(i)),gl.POINTS,[1,.69,.36,1],6);
 $('anatomy-note').textContent=`${pts.length} recorded positions · ${edgeVertices.length/4} sampled edges · XY projection`;
 c.onclick=e=>{const r=c.getBoundingClientRect(),x=2*(e.clientX-r.left)/r.width-1,y=1-2*(e.clientY-r.top)/r.height;let best=0,d=Infinity;pts.forEach((v,i)=>{const distance=(coords[2*i]*.94-x)**2+(coords[2*i+1]*.94-y)**2;if(distance<d){d=distance;best=i;}});$('body').value=anatomy.body_ids[pts[best].i];};
}
$('edge-limit').onchange=drawAnatomy;
$('population').onchange=drawAnatomy;$('inspect').onclick=async()=>{try{$('connections').textContent=JSON.stringify(await api('/connection?body='+encodeURIComponent($('body').value)),null,2);}catch(e){$('connections').textContent=e.message;}};
$('run-probe').onclick=()=>command('probe',{probe:{kind:$('probe').value,polarity:$('polarity').value,direction:+$('direction').value,speed:+$('probe-speed').value,x:+$('probe-x').value,y:+$('probe-y').value,radius:+$('probe-radius').value},checkpoint_index:+$('probe-checkpoint').value,silenced_types:$('silence').value.split(',').map(s=>s.trim()).filter(Boolean)});
let lastDrawnStep=-1;
let bundleIds=[],bundles=[null,null];
async function refreshBundles(){const ids=await api('/diagnostics');if(ids.join()===bundleIds.join())return;bundleIds=ids;for(const id of ['bundle-a','bundle-b']){const select=$(id),value=select.value;select.replaceChildren(new Option('Select a saved probe',''),...ids.map((key,i)=>new Option(`Probe ${i+1} · ${key.slice(-8)}`,key)));select.value=value;}}
async function loadBundle(slot){const id=$(slot?'bundle-b':'bundle-a').value;bundles[slot]=id?await api('/diagnostic?id='+encodeURIComponent(id)):null;const names=[...new Set(bundles.flatMap(b=>Object.keys(b?.populations||{})))].sort(),current=$('response-type').value;$('response-type').replaceChildren(...names.map(n=>new Option(n,n)));if(names.includes(current))$('response-type').value=current;drawResponses();replayProbe();}
function drawResponses(){const type=$('response-type').value,c=$('responses'),g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);const rows=bundles.map(b=>b?.populations[type]);const max=Math.max(.001,...rows.flatMap(r=>r?.response||[]));rows.forEach((r,slot)=>{if(!r)return;g.strokeStyle=slot?'#efa376':'#86d8bf';g.beginPath();r.response.forEach((v,i)=>{const x=i*c.width/Math.max(1,r.response.length-1),y=c.height-10-v/max*(c.height-20);i?g.lineTo(x,y):g.moveTo(x,y);});g.stroke();});$('diagnostic-note').textContent='A: green · B: orange · fraction of population spiking per neural tick';$('diagnostic').textContent=JSON.stringify(bundles.map((b,i)=>b?{response:i?'B':'A',checkpoint:b.checkpoint_sha256,stimulus:b.stimulus,silenced:b.silenced_types,cell_type:type,...Object.fromEntries(Object.entries(b.populations[type]||{}).filter(([k])=>k!=='response'))}:null),null,2);}
function replayProbe(){const b=bundles[0];if(!b)return;$('probe-tick').max=b.replay.length-1;const tick=Math.min(+$('probe-tick').value,b.replay.length-1),frame=b.replay[tick],c=$('probe-replay'),g=c.getContext('2d');g.fillStyle='#0b1118';g.fillRect(0,0,c.width,c.height);g.fillStyle='#dbe5ed';frame.pixels.forEach(p=>g.fillRect((p%b.width)*c.width/b.width,Math.floor(p/b.width)*c.height/b.height,c.width/b.width,c.height/b.height));const indices=new Map((anatomy?.body_ids||[]).map((body,i)=>[body,i]));recentSpikes=frame.spike_bodies.filter(body=>indices.has(body)).map(body=>indices.get(body));drawAnatomy();}
$('bundle-a').onchange=()=>loadBundle(0).catch(e=>$('message').textContent=e.message);$('bundle-b').onchange=()=>loadBundle(1).catch(e=>$('message').textContent=e.message);$('response-type').onchange=drawResponses;$('probe-tick').oninput=replayProbe;
async function poll(){try{const s=await api('/status');if(!s.waiting){$('status').textContent=s.stopped?'Stopped':s.paused?'Paused':'Running';if(s.step!==lastDrawnStep){pong(s);evaluationViews(s);recentSpikes=s.spiking_neurons||[];if(anatomy)drawAnatomy();lastDrawnStep=s.step;}metrics(s);$('log').textContent=(s.logs||[]).join('\n')||'Worker active.';}else{$('status').textContent='Awaiting worker';}if(config.evaluation){await refreshBundles();}}catch(e){$('status').textContent='UI disconnected';$('message').textContent=e.message;}setTimeout(poll,500);}
api('/config').then(async c=>{config=c;$('mode').textContent=`${c.evaluation?'Frozen evaluation':'Training'} · ${c.checkpoint}`;document.querySelectorAll('.evaluation').forEach(e=>e.hidden=!c.evaluation);document.querySelectorAll('.training').forEach(e=>e.hidden=c.evaluation);if(c.evaluation){c.checkpoints.forEach((name,i)=>{const o=document.createElement('option');o.value=i;o.textContent=name;$('probe-checkpoint').append(o);});anatomy=await api('/anatomy');[...new Set(anatomy.cell_types)].sort().forEach(t=>{const o=document.createElement('option');o.value=o.textContent=t;$('population').append(o);});drawAnatomy();}poll();}).catch(e=>$('message').textContent=e.message);
